// Generated TypeScript types from Go structs
// DO NOT EDIT MANUALLY - Run 'npm run generate:types' to regenerate
// 
// Source: backend/models/*.go, backend/server/ws/messages.go
// Tool: github.com/skia-dev/go2ts
// 
// These types ensure frontend-backend contract alignment

/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-explicit-any */
// DO NOT EDIT. This file is automatically generated.

export interface TargetPayload {
	TargetIndex: number;
}

export interface AccusePayload {
	TargetIndex: number;
	Guess: Role;
}

export interface NoPayload {
}

export interface PlayerAction {
	ID: ActionID;
	SourceIndex: number;
	Payload: any;
	MainAction: ActionID;
}

export interface HelloPayload {
	nickname: string;
	reconnect_token?: string;
	avatar?: string;
}

export interface HelloAckPayload {
	player_id: string;
	token: string;
}

export interface HelloErrorPayload {
	error: string;
}

export interface LobbyJoinPayload {
	lobby_id: string;
}

export interface LobbyStartPayload {
	lobby_id: string;
}

export interface LobbyCreatedPayload {
	lobby_id: string;
}

export interface LobbySummaryPayload {
	id: string;
	leader_nick: string;
	leader_id: string;
	player_count: number;
	player_nicks?: string[] | null;
	player_ids?: string[] | null;
	player_avatars?: string[] | null;
	status: string;
}

export interface LobbyListPayload {
	lobbies: LobbySummaryPayload[] | null;
}

export interface LobbyStatePayload {
	lobby_id: string;
	leader_nick: string;
	leader_id: string;
	player_nicks: string[] | null;
	player_ids: string[] | null;
	player_avatars?: string[] | null;
	player_count: number;
	status: string;
}

export interface LobbyStartedPayload {
	lobby_id: string;
	match_id: string;
	player_index: number;
	player_count: number;
	player_names: string[] | null;
	player_avatars?: string[] | null;
	index_mapping: { [key: string]: number } | null;
}

export interface ChatMessagePayload {
	id: string;
	senderIndex: number;
	senderName: string;
	text: string;
	timestamp: number;
}

export interface ActionPayload {
	id: ActionID;
	source_index: number | null;
	target_index?: number | null;
	guess?: string | null;
	main_action?: ActionID | null;
	pass?: boolean;
}

export interface ChallengePayload {
	challenger_index: number | null;
	challenger_discard_index: number;
	actor_discard_index: number;
	actor_proving_card_index: number;
	pass?: boolean;
}

export interface RequestActionPayload {
	actor_index: number;
	allowed_actions?: ActionID[] | null;
	prompt?: string;
}

export interface RequestStepPayload {
	step: any;
	prompt?: string;
}

export interface ChallengeWindowPayload {
	actor_index: number;
	action_id: string;
	claimed_role: string;
	kind: string;
	target_index?: number | null;
	eligible: boolean;
	timeout_ms?: number;
	prompt?: string;
}

export interface CounterWindowPayload {
	actor_index: number;
	action_id: string;
	allowed_actions?: ActionID[] | null;
	target_index?: number | null;
	eligible: boolean;
	timeout_ms?: number;
	prompt?: string;
}

export interface GameLogPayload {
	turn: number;
	scope: string;
	message: string;
	player_index?: number | null;
}

export interface GameOverPayload {
	winner_index: number;
	winner_name: string;
}

export interface PlayerStatePayload {
	index: number;
	name: string;
	coins: number;
	card_count: number;
	alive: boolean;
	avatar?: string;
}

export interface GameStatePayload {
	turn_number: number;
	active_player_index: number;
	players: PlayerStatePayload[] | null;
}

export interface GameConfigPayload {
	roles: string[] | null;
}

export interface PromptClosedPayload {
	reason: string;
}

export interface InvestigateResultPayload {
	target_name: string;
	role: string;
}

export interface HandStatePayload {
	player_index: number;
	hand: string[] | null;
}

export interface PlayerEliminatedPayload {
	player_index: number;
	reason: string;
	turn: number;
}

export interface TurnTimerPayload {
	active_player_index: number;
	turn_number: number;
	duration_ms: number;
	state: string;
}

export interface GamePausedPayload {
	paused_by_player_id: string;
	paused_by_index: number;
	paused_by_name: string;
	deadline_ms: number;
	duration_ms: number;
	pause_reason: string;
	eligible_voters: number[] | null;
	kick_votes: number[] | null;
}

export interface GameResumedPayload {
	resumed_by_player_id: string;
	resumed_by_index: number;
	resumed_by_name: string;
	resume_reason: string;
}

export interface KickVotePayload {
	target_index: number;
}

export interface KickVoteUpdatePayload {
	eligible_voters: number[] | null;
	kick_votes: number[] | null;
}

export interface PlayerKickedPayload {
	player_index: number;
	reason: string;
}

export type ActionID = string;

export type Role = string;

export type ActionKind = string;
